### ISSUE TITLE
Allow <del>tag deletion</del> empty tags

### ISSUE THREAD

**Issue by Biep** [turt2live/matrix-tag-manager#8]
Maybe related to #5 - allow the deletion of tags that have no rooms.
#5 could then be implemented by creation, mass movement, and deletion.

**Comment by Biep** [comment]
Oh wait - # 4 already covered this.
If the tag is indeed truly gone (not offered as an option when right-clicking the room in the list) then I turn my request around:
Allow the creation of as-yet unused tags.
I help set up matrix/Riot for many people, often in structured situations.  I'd like to provide them with a bunch of tags that will be useful for them to sort their rooms in their specific context.  That includes currently-unused tags.

**Comment by turt2live** [comment]
Tags are associated to rooms - you can already create as many columns as you want, though if you add no rooms to those tags then they don't actually exist. 

This would require spec work to fix otherwise.

**Comment by Biep** [comment]
The use of empty tags would be that users can later move rooms to those categories, without having to use (or know about) the tag manager.
